"use client";

import { client } from "@/better-agent/client";
import { useAgent } from "@better-agent/client/react";
import { useState } from "react";

type TextPart = Extract<
  ReturnType<typeof useAgent<typeof client>>["messages"][number]["parts"][number],
  { type: "text" }
>;

type ToolCallPart = Extract<
  ReturnType<typeof useAgent<typeof client>>["messages"][number]["parts"][number],
  { type: "tool-call" }
>;

type ToolResultPart = Extract<
  ReturnType<typeof useAgent<typeof client>>["messages"][number]["parts"][number],
  { type: "tool-result" }
>;

const dedupeByCallId = <T extends { callId: string }>(parts: T[]) =>
  Array.from(new Map(parts.map((part) => [part.callId, part])).values());

const formatJson = (value: unknown) => {
  if (typeof value === "string") {
    try {
      return JSON.stringify(JSON.parse(value), null, 2);
    } catch {
      return value;
    }
  }

  if (value === undefined) {
    return "";
  }

  try {
    return JSON.stringify(value, null, 2);
  } catch {
    return String(value);
  }
};

const getToolTone = (status: "pending" | "success" | "error") =>
  status === "error"
    ? "border-red-500/30 bg-red-500/10 text-red-100"
    : status === "success"
      ? "border-emerald-500/30 bg-emerald-500/10 text-emerald-100"
      : "border-cyan-500/30 bg-cyan-500/10 text-cyan-100";

const getToolStatusLabel = (part: ToolCallPart) => {
  if (part.status === "error") return "error";
  if (part.status === "success") return "success";
  if (part.state === "input-complete") return "queued";
  if (part.state === "input-streaming") return "building args";
  return "running";
};

const getToolResultSummary = (toolName: string | undefined, result: unknown) => {
  if (!result || typeof result !== "object") {
    return "工具执行完成";
  }

  const payload = result as {
    weather?: string;
    location?: string;
    message?: string;
    type?: string;
  };

  if (payload.type === "tool_error") {
    return payload.message ?? "工具执行失败";
  }

  if (toolName === "get_weather" && typeof payload.weather === "string") {
    return payload.weather;
  }

  if (typeof payload.location === "string") {
    return `工具已返回 ${payload.location} 的结果`;
  }

  return "工具执行完成";
};

export default function Page() {
  const [input, setInput] = useState("");
  const { messages, status, error, sendMessage, stop } = useAgent(client, {
    agent: "openai",
    conversationId: "main",
    hydrateFromServer: true,
    resume: true,
  });

  return (
    <main className="min-h-screen bg-[color:var(--background)] px-4 py-6 text-[color:var(--foreground)] sm:px-6 sm:py-8">
      <section className="mx-auto grid max-w-3xl gap-4">
        <header className="grid gap-3">
          <p className="m-0 font-mono text-[11px] uppercase tracking-[0.08em] text-[color:var(--muted)]">
            Generated by Better Agent
          </p>
          <h1 className="m-0 text-[1.85rem] font-semibold tracking-[-0.05em] text-white sm:text-[2.2rem]">
            Next.js Starter Chat
          </h1>
          <div className="flex items-center gap-2 border border-[color:var(--border)] bg-[color:var(--panel)] px-3 py-2 font-mono text-[11px] uppercase tracking-[0.2em] text-[color:var(--muted)]">
            <span className="text-white/55">&gt;_</span>
            <span className="text-white/78">/agents/openai</span>
          </div>
        </header>

        <section className="grid gap-3 border border-[color:var(--border)] bg-[color:var(--panel)] p-3 sm:p-4">
          <div className="flex items-center justify-between gap-3 font-mono text-[11px] uppercase tracking-[0.22em] text-[color:var(--muted)]">
            <span>conversation main</span>
            <span>{status}</span>
          </div>

          <section
            className="grid min-h-[320px] gap-3 border border-[color:var(--border)] bg-[color:var(--panel-muted)] p-3"
            aria-live="polite"
          >
            {messages.length === 0 ? (
              <div className="grid place-items-center border border-dashed border-[color:var(--border)] px-4 py-12 text-center text-sm leading-6 text-[color:var(--muted)]">
                No messages yet.
              </div>
            ) : (
              <div className="grid content-start gap-3 self-start">
                {messages.map((message) => {
                  const textParts = message.parts.filter(
                    (part): part is TextPart => part.type === "text",
                  );
                  const toolCallParts = dedupeByCallId(
                    message.parts.filter(
                      (part): part is ToolCallPart => part.type === "tool-call",
                    ),
                  );
                  const toolResultParts = dedupeByCallId(
                    message.parts.filter(
                      (part): part is ToolResultPart => part.type === "tool-result",
                    ),
                  );

                  return (
                    <article
                      key={message.localId}
                      className={`max-w-[88%] border px-2.5 py-2 text-sm leading-[1.55] ${
                        message.role === "user"
                          ? "ml-auto border-[color:var(--border-strong)] bg-white text-black"
                          : "border-[color:var(--border)] bg-black text-[color:var(--foreground)]"
                      }`}
                    >
                      <p
                        className={`m-0 font-mono text-[9px] uppercase tracking-[0.18em] ${
                          message.role === "user"
                            ? "text-black/55"
                            : "text-[color:var(--muted)]"
                        }`}
                      >
                        {message.role}
                      </p>

                      {toolCallParts.length > 0 || toolResultParts.length > 0 ? (
                        <div className="mt-2 grid gap-2">
                          {toolCallParts.map((part) => (
                            <section
                              key={`call-${part.callId}`}
                              className={`grid gap-2 border px-3 py-2 ${getToolTone(part.status)}`}
                            >
                              <div className="flex items-center justify-between gap-3 font-mono text-[10px] uppercase tracking-[0.18em]">
                                <span>{part.name ?? "tool"}</span>
                                <span>{getToolStatusLabel(part)}</span>
                              </div>
                              <div className="font-mono text-[10px] uppercase tracking-[0.18em] opacity-75">
                                {part.toolTarget ?? "server"} tool
                              </div>
                              {part.args ? (
                                <pre className="m-0 overflow-x-auto whitespace-pre-wrap break-words border border-white/10 bg-black/30 px-3 py-2 font-mono text-[12px] leading-5 text-white/85">
                                  {formatJson(part.args)}
                                </pre>
                              ) : null}
                            </section>
                          ))}

                          {toolResultParts.map((part) => {
                            const toolCall = toolCallParts.find(
                              (toolPart) => toolPart.callId === part.callId,
                            );
                            const toolName = toolCall?.name;

                            return (
                              <section
                                key={`result-${part.callId}`}
                                className={`grid gap-2 border px-3 py-2 ${getToolTone(part.status)}`}
                              >
                                <div className="flex items-center justify-between gap-3 font-mono text-[10px] uppercase tracking-[0.18em]">
                                  <span>{toolName ? `${toolName} result` : "tool result"}</span>
                                  <span>{part.status}</span>
                                </div>
                                <p className="m-0 text-sm leading-6">
                                  {getToolResultSummary(toolName, part.result)}
                                </p>
                                {part.result ? (
                                  <pre className="m-0 overflow-x-auto whitespace-pre-wrap break-words border border-white/10 bg-black/30 px-3 py-2 font-mono text-[12px] leading-5 text-white/85">
                                    {formatJson(part.result)}
                                  </pre>
                                ) : null}
                              </section>
                            );
                          })}
                        </div>
                      ) : null}

                      {textParts.length > 0 ? (
                        <div className="mt-2 grid gap-2">
                          {textParts.map((part, index) => (
                            <p key={`${message.localId}-text-${index}`} className="m-0 whitespace-pre-wrap">
                              {part.text}
                            </p>
                          ))}
                        </div>
                      ) : null}

                      {textParts.length === 0 &&
                      toolCallParts.length === 0 &&
                      toolResultParts.length === 0 ? (
                        <p className="m-0 mt-1.5 whitespace-pre-wrap text-[color:var(--muted)]">
                          No renderable content
                        </p>
                      ) : null}
                    </article>
                  );
                })}
              </div>
            )}
          </section>

          <form
            className="grid gap-3"
            onSubmit={async (event) => {
              event.preventDefault();
              if (status === "submitted" || status === "streaming") {
                stop();
                return;
              }
              const value = input.trim();
              if (!value) return;
              setInput("");
              await sendMessage(value);
            }}
          >
            <textarea
              value={input}
              onChange={(event) => setInput(event.target.value)}
              placeholder="Ask something..."
              aria-label="Message"
              className="min-h-[96px] w-full resize-none border border-[color:var(--border)] bg-black px-3 py-2.5 text-sm leading-6 text-[color:var(--foreground)] outline-none transition placeholder:text-[color:var(--muted)] focus:border-[color:var(--border-strong)]"
            />
            <div className="flex flex-wrap items-center justify-end gap-3">
              <div className="flex items-center gap-2">
                <button
                  type="button"
                  onClick={() => stop()}
                  disabled={status !== "submitted" && status !== "streaming"}
                  className="border border-[color:var(--border)] px-3 py-2 text-sm text-[color:var(--foreground)] transition hover:border-[color:var(--border-strong)] disabled:cursor-not-allowed disabled:opacity-40"
                >
                  Stop
                </button>
                <button
                  type="submit"
                  disabled={
                    status === "submitted" ||
                    status === "streaming" ||
                    input.trim().length === 0
                  }
                  className="border border-white bg-white px-3 py-2 text-sm font-medium text-black transition hover:bg-white/90 disabled:cursor-not-allowed disabled:opacity-40"
                >
                  {status === "submitted" || status === "streaming"
                    ? "Streaming"
                    : "Send"}
                </button>
              </div>
            </div>
            {error ? (
              <p className="m-0 border border-red-500/40 bg-red-500/10 px-3 py-2 text-sm text-red-200">
                {error.message}
              </p>
            ) : null}
          </form>
        </section>
      </section>
    </main>
  );
}
